Update pylint.yml

diff --git a/.github/workflows/pylint.yml b/.github/workflows/pylint.yml
--- a/.github/workflows/pylint.yml
+++ b/.github/workflows/pylint.yml
@@ -9,15 +9,23 @@ jobs:
       matrix:
         python-version: ["3.11"]
     steps:
-    - uses: actions/checkout@v4
-    - name: Set up Python ${{ matrix.python-version }}
-      uses: actions/setup-python@v3
-      with:
-        python-version: ${{ matrix.python-version }}
-    - name: Install dependencies
-      run: |
-        python -m pip install --upgrade pip
-        pip install pylint
-    - name: Analysing the code with pylint
-      run: |
-        pylint $(git ls-files '*.py')
+      - uses: actions/checkout@v4
+      - name: Set up Python ${{ matrix.python-version }}
+        uses: actions/setup-python@v3
+        with:
+          python-version: ${{ matrix.python-version }}
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install pylint
+      - name: Analysing the code with pylint
+        run: |
+          score=$(pylint $(git ls-files '*.py') | tee /dev/tty | grep -oP '(?<=Your code has been rated at )[-+]?[0-9]*\.?[0-9]+' | tail -1)
+          echo "Pylint score: $score"
+          if (( $(echo "$score > 6" | bc -l) )); then
+            echo "✅ Pylint score is greater than 6, passing the build"
+            exit 0
+          else
+            echo "❌ Pylint score is less than 6, failing the build"
+            exit 1
+          fi
